### ISSUE TITLE
General comments

### ISSUE THREAD

**Issue by rkrug** [jkumagai96/Technical-Guideline-Series#1]
This is just. a list of comments and point which should be fixed of considered.

Overall, it reads very nice and I have learned a few things. Thanks.

I still think, it would be useful to bundle all these as vignettes into an R package - but the format has to fir the IPBES ICS format.

### General comments

- [x] When looking at the html on the iPad in portrait mode, the logo overlaps the text. Maybe change the logo to png and make the white background transparent?
- [ ] Put the logos underneath each other?
- [x] It is a matter of taste (well - not only), ut it may be useful to use the `PACKAGE::FUNCTION()` notation. By doing this, it is clear, which command comes from which package, and makes it easier to reproduce the code, as the order in which the packages are loaded, will not play a role (they will, when packages have functions of the same names, as the last one loaded is used).

### Technical Guidelines Part 1

- [x]  Make sure that there are no warnings in your examples - if there are, you should explain them 
- [ ] Isn't the Robinson projection predefined?
- [x] open links in new tabs, to still have to original document open (probably not necessary for final format?). 
- [x] 1.1 Maybe use a real map, to show it better? You will also see the change when retrojecting to Robinson
- [x] Are there any points one has to consider? Limits of the re-projection? Is the re-projection lossless? Only for visualisation or also analysis?
- [x] Also add a disclaimer as in Part 2

### Technical Guidelines Part 2

- [x] Dependency `library(tidyverse)` is bad. Tidyverse is a huge number of packages, and usually only a small number is needed. Try `dplyr`, `magritter` - could already work.
- [x]  Why don't you use the FAOSTAT package to download the data from FAOSTAT?
- [ ] B: Downloading from Zenodo: This is an extremely useful little tidbit of code. May I suggest, to put this into a small pR package? I am happy to help.

### Technical Guidelines Part 3

- [x] Dependency `library(tidyverse)` is bad. Tidyverse is a huge number of packages, and usually only a small number is needed. Try `dplyr`, `magritter` - could already work.
- [x] A: If Antarctica is a cartographic element, what about the other continents?
- [x] B.: Projections - very vague wording. There has no decision by IPBES concerning the marine and Pacific themes and the country, region maps?
- [x] Colour: Please add to use it consistently in maps (also in graphs, but that is a different issue).
- [x] III. Suggestions: Please specify colours as above:  (BBBBBB; RGB:187, 187, 187)
- [x] Please add colour specification for 'light sky blue'
- [x] Please add: Use colour schemes and projections consistently throughout the chapter, if possible throughout the assessment. Colour schemes should also be consistent with the ones used for figures.

**Comment by jkumagai96** [comment]
Technical Guidelines - Part 3 has been updated to include your suggestions (thank you for them). For projections, the wording is derived from the UNEP guidelines from their dedicated mapping section. I don't believe there has been a decision by IPBES, but I will double check with Aidin.

**Comment by rkrug** [comment]
Thanks Joy!

These Technical Guidelines are screaming "vignettes" in an IPBES paper, which contains all the functions to make this easier.

**Comment by rkrug** [comment]
Could you please check the warnings? To get rid of them, just reinstall the packages and re-knit. Should work.
