### ISSUE TITLE
Outline of repository

### ISSUE THREAD

**Issue by rkrug** [jkumagai96/Technical-Guideline-Series#2]
May I suggest two things for the GitHub site:

1. make one folder named `source` in which you put the .rmd files
2. make one folder named `web` in which you put all the final html files
3. add `Readme.Rmd` (or `.md` file which can than be knitted to an html file in the `web` folder. This file contains links to all the html guides and the official ist site.
4. use GitHub Pages to publish the folder `web` as a website

By doing this, one can see the documents on the GitHub page directly.

I am using a makefile for this kind of thing...

**Comment by jkumagai96** [comment]
I organized the code into the two folders you recommended, source and web and added an readme.md file. I am still working on configuring the github pages to work properly.

**Comment by rkrug** [comment]
If you have questions, let me know. I have a few GitHub Pages .

**Comment by jkumagai96** [comment]
https://jkumagai96.github.io/Technical-Guideline-Series/

**Comment by rkrug** [comment]
Looks very nice!

If you have a DOI for this repo, please add it to the index.
